server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mashrabbek/config-server
          clone-on-start: true
          default-label: main
          search-paths:
            - '{application}'
            - '{application}/{profile}'
            - 'shared'
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          skip-ssl-validation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env

logging:
  level:
    org.springframework.cloud.config: DEBUG
    root: INFO
