spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: product-composite
            uri: lb://product-composite
            predicates:
              - Path=/product-composite/**

          - id: product-composite-swagger-ui
            uri: lb://product-composite
            predicates:
              - Path=/openapi/**

          - id: eureka-api
            uri: http://${app.eureka-server}:8761
            predicates:
              - Path=/eureka/api/{segment}
            filters:
              - SetPath=/eureka/{segment}

          - id: eureka-web
            uri: http://${app.eureka-server}:8761
            predicates:
              - Path=/eureka/**
            filters:
              - SetPath=/

          - id: actuator
            uri: forward:/actuator
            predicates:
              - Path=/actuator/**

server:
  port: 8080

app:
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker

app:
  eureka-server: eureka
