spring:
    application:
      name: review-service

server:
    port: 7003
    error:
      include-message: always

logging:
  level:
    root: INFO
    com.example: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
